#!/usr/bin/env bash
set -euo pipefail

# Runpod H100 SXM setup script
# Usage: bash setup.sh
# Must be run as root (default on Runpod)

echo "=== CoT Editing Exploration - Runpod Setup ==="

# Parallel compilation jobs (H100 SXM has many cores)
export MAX_JOBS=8

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── 1. System dependencies ──
echo "Installing system dependencies..."
apt-get update -qq && apt-get install -y -qq curl git tmux > /dev/null

# ── 2. Create sandbox user for isolated code execution (no home dir, no login shell) ──
if ! id -u sandbox &>/dev/null; then
    echo "Creating sandbox user for code execution isolation..."
    useradd -r -s /usr/sbin/nologin -M sandbox
fi

# Allow sandbox user to traverse /root/ to reach the uv-installed Python binary.
# Only adds execute (traverse) permission, not read (listing).
chmod o+x /root

# ── 3. Install uv system-wide ──
if ! command -v uv &>/dev/null; then
    echo "Installing uv..."
    curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR=/usr/local/bin sh
fi
echo "uv: $(uv --version)"

# ── 4. Install Claude Code (native installer, includes Node.js) ──
if ! command -v claude &>/dev/null; then
    echo "Installing Claude Code..."
    curl -fsSL https://claude.ai/install.sh | bash
    export PATH="$HOME/.local/bin:$PATH"
fi
echo "claude: $(claude --version)"

# Make claude accessible system-wide (installer puts it in /root/.local/bin)
CLAUDE_BIN=$(readlink -f "$(which claude)")
if [ -n "$CLAUDE_BIN" ] && [ ! -e /usr/local/bin/claude ]; then
    ln -sf "$CLAUDE_BIN" /usr/local/bin/claude
    echo "Symlinked claude to /usr/local/bin for non-root users"
fi

# ── 6. Initialize git submodules (datasets) ──
echo "Initializing submodules..."
cd "$PROJECT_DIR"
git submodule update --init --recursive

# ── 7. Install project dependencies ──
echo "Installing dependencies with uv..."
cd "$PROJECT_DIR"
# Remove stale .venv to avoid NFS "stale file handle" errors on re-runs
if [ -d .venv ]; then
    echo "Removing existing .venv (avoids stale NFS handles)..."
    rm -rf .venv
fi
UV_LINK_MODE=copy uv sync

# ── 8. Create claude-user for running Claude Code ──
CLAUDE_USER="claude-user"
if ! id -u "$CLAUDE_USER" &>/dev/null; then
    echo "Creating $CLAUDE_USER user..."
    useradd -m -s /bin/bash "$CLAUDE_USER"
fi
CLAUDE_USER_HOME=$(eval echo "~$CLAUDE_USER")

# Give claude-user read/write access to the project directory.
# chown -R fails on /workspace (NFS mount), so use chmod + ACLs or just ensure
# world-readable/writable for the project. We chown what we can and ignore errors
# on filesystem boundaries.
chown -R "$CLAUDE_USER":"$CLAUDE_USER" "$PROJECT_DIR" 2>/dev/null || true

# Mark project dirs as safe for git (avoids "dubious ownership" errors)
su - "$CLAUDE_USER" -c "git config --global --add safe.directory '$PROJECT_DIR'"
su - "$CLAUDE_USER" -c "git config --global --add safe.directory '$PROJECT_DIR/src/rl-rewardhacking'"

# ── 9. Set up environment for claude-user ──
# Write to .bash_profile so it's sourced by login shells (su - user -c '...')
# .bashrc is NOT sourced by non-interactive login shells on Ubuntu.
cat > "$CLAUDE_USER_HOME/.bash_profile" <<'PROFILE_EOF'
# Tool paths — uv and node are installed system-wide (/usr/local/bin)
export PATH="/usr/local/bin:$HOME/.local/bin:$PATH"

# Source .env file for API keys (created by setup.sh)
[ -r "$HOME/.claude_env" ] && . "$HOME/.claude_env"

# Source .bashrc if it exists (for interactive shells)
[ -r "$HOME/.bashrc" ] && . "$HOME/.bashrc"
PROFILE_EOF

# Propagate API keys into a restricted env file
touch "$CLAUDE_USER_HOME/.claude_env"
chmod 600 "$CLAUDE_USER_HOME/.claude_env"
cat > "$CLAUDE_USER_HOME/.claude_env" <<ENV_EOF
# API keys — auto-generated by setup.sh, chmod 600
ENV_EOF

if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    echo "export ANTHROPIC_API_KEY='$ANTHROPIC_API_KEY'" >> "$CLAUDE_USER_HOME/.claude_env"
    echo "ANTHROPIC_API_KEY propagated to $CLAUDE_USER"
else
    echo "WARNING: ANTHROPIC_API_KEY not set. Set it and re-run, or add manually to $CLAUDE_USER_HOME/.claude_env"
fi

if [ -n "${WANDB_API_KEY:-}" ]; then
    echo "export WANDB_API_KEY='$WANDB_API_KEY'" >> "$CLAUDE_USER_HOME/.claude_env"
    echo "WANDB_API_KEY propagated to $CLAUDE_USER"
fi

chown -R "$CLAUDE_USER":"$CLAUDE_USER" "$CLAUDE_USER_HOME"

# ── 10. Configure Claude Code hooks for root and claude-user ──
echo "Configuring Claude Code hooks..."
HOOKS_JSON='{
  "hooks": {
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "curl -s -d '\''Claude has finished.'\'' https://ntfy.sh/sz-jazon-claude-code"
          }
        ]
      }
    ]
  }
}'

# Root
mkdir -p /root/.claude
echo "$HOOKS_JSON" > /root/.claude/settings.json

# claude-user
CLAUDE_CONFIG_DIR="$CLAUDE_USER_HOME/.claude"
mkdir -p "$CLAUDE_CONFIG_DIR"
echo "$HOOKS_JSON" > "$CLAUDE_CONFIG_DIR/settings.json"
chown -R "$CLAUDE_USER":"$CLAUDE_USER" "$CLAUDE_CONFIG_DIR"

# ── 11. wandb setup ──
echo ""
echo "=== wandb setup ==="
if [ -z "${WANDB_API_KEY:-}" ]; then
    echo "Set WANDB_API_KEY env var or run: uv run wandb login"
else
    echo "WANDB_API_KEY detected"
fi

# ── Done ──
echo ""
echo "=== Setup complete ==="
echo ""
echo "To run Claude Code as $CLAUDE_USER (dangerously skip permissions):"
echo "  su - $CLAUDE_USER -c 'cd $PROJECT_DIR && claude --dangerously-skip-permissions'"
echo ""
echo "To run Claude headless:"
echo "  su - $CLAUDE_USER -c 'cd $PROJECT_DIR && claude -p \"your prompt\" --dangerously-skip-permissions'"
echo ""
echo "To run training:"
echo "  su - $CLAUDE_USER -c 'cd $PROJECT_DIR && uv run python -m steering.train'"
